version: 2.1
jobs:
  compile:
   docker:
      - image: azrim89/kernel:latest
   steps:
      - run:
          command: |
            git config --global user.name "fakeriz"
            git config --global user.email "hafizharrizqa15@gmail.com"
            git clone https://github.com/Zombie-Prjkt/kernel_xiaomi_surya-1.git -b staging --depth=1
            wget https://raw.githubusercontent.com/Zombie-Prjkt/zKernelCompiler/main/circleci.sh
            bash /root/project/kernel_xiaomi_surya-1/circleci.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile